### ISSUE TITLE
[meta] Allow destination path to be customizable

### ISSUE THREAD

**Issue by jmathai** [jmathai/elodie#111]
Meta issue for allowing the generated file name to be customized. Currently the file name contains 3 parts. `yyyy-mm-dd_mm-hh-ss-{file-name}-{title-from-exif}.{extension}` is the default and `-{title-from-exif}` is omitted if not found.

We should have a format syntax that overrides the current behavior which would remain the default. Something like `--filename-format="%Y-%m-%d_%H-%M-%S-%FILENAME%.%EXTENSION%"`. In the case of #110 it would just be `--filename-format="%FILENAME.%EXTENSION%"`.
- [x] #5 allow folder name/structure to be customized
- [x] #107 omit `{file-name}` from file name
- [x] #110 omit `yyyy-mm-dd_mm-hh-ss` from file name

**Comment by jmathai** [comment]
Destination file name is now configurable. Docs are [here](https://github.com/jmathai/elodie#how-file-customization-works). I added a bunch of tests to make sure it's backwards compatible but nothing is better than real world usage to see if there are any bugs. Please try it out.
